# training_params.yaml

# General Training Parameters
training:
  num_epochs: 1000
  batch_size: 32
  learning_rate: 0.001
  num_folds: 5
  output_dir: '/content/drive/MyDrive/colab_nb/models/saved'

# Data Augmentation Parameters
augmentations:
  resize_scale: [0.9, 1.0]
  horizontal_flip: 0.1
  vertical_flip: 0
  rotation_degrees: 5
  brightness: 0.1
  contrast: 0.1
  saturation: 0.1
  hue: 0.05
  gaussian_blur_kernel: [3, 5]
  gamma_range: [0.9, 1.1]
  erasing_scale: [0.02, 0.05]
  erase_ratio: [0.5, 2.0]


# Logging and Versioning
logging:
  version_prefix: 'AquaGrade-v'
  save_metrics: true
  log_dir: 'content/drive/MyDrive/colab_nb/aquagrade_pkg/models/'
