# * List of class names in the dataset
class_names:
- Galunggong-SKIN -0-
- Galunggong-SKIN -1-
- Galunggong-SKIN -2-
- Galunggong-GILL-COVER -0-
- Galunggong-GILL-COVER -1-
- Galunggong-GILL-COVER -2-
- Galunggong-GILL-COVER -3-
- Galunggong-EYE-CLARITY -0-
- Galunggong-EYE-CLARITY -1-
- Galunggong-EYE-SHAPE -0-
- Galunggong-EYE-SHAPE -1-
- Galunggong-EYE-SHAPE -2-
- Tilapia-SKIN -0-
- Tilapia-SKIN -1-
- Tilapia-SKIN -2-
- Tilapia-GILL-COVER -0-
- Tilapia-GILL-COVER -1-
- Tilapia-GILL-COVER -2-
- Tilapia-GILL-COVER -3-
- Tilapia-EYE-CLARITY -0-
- Tilapia-EYE-CLARITY -1-
- Tilapia-EYE-SHAPE -0-
- Tilapia-EYE-SHAPE -1-
- Tilapia-EYE-SHAPE -2-
- Bangus-SKIN -0-
- Bangus-SKIN -1-
- Bangus-SKIN -2-
- Bangus-GILL-COVER -0-
- Bangus-GILL-COVER -1-
- Bangus-GILL-COVER -2-
- Bangus-GILL-COVER -3-
- Bangus-EYE-CLARITY -0-
- Bangus-EYE-CLARITY -1-
- Bangus-EYE-SHAPE -0-
- Bangus-EYE-SHAPE -1-
- Bangus-EYE-SHAPE -2-